[package]
name = "wat"
version = "1.0.17"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
repository = "https://github.com/bytecodealliance/wat"
homepage = "https://github.com/bytecodealliance/wat"
documentation = "https://docs.rs/wat"
description = """
Rust parser for the WebAssembly Text format, WAT
"""
exclude = ['tests/wabt', 'tests/testsuite']

[workspace]
members = ['fuzz']

[dependencies]
wast = { path = 'crates/wast', version = '16.0.0' }

[dev-dependencies]
anyhow = "1.0"
getopts = "0.2"
rayon = "1.0"
serde_json = "1.0"
tempfile = "3.1"
wasmparser = "0.53"

[profile.release]
debug-assertions = true
overflow-checks = true
debug = 1

[[test]]
name = "wabt"
harness = false

[[test]]
name = "parse-fail"
harness = false
